### ISSUE TITLE
"No plot specified" when using save only.

### ISSUE THREAD

**Issue by kasuteru** [ARM-DOE/dv#12]
Maybe I am doing something wrong - on Windows 10, with Chrome.

I run:

`python3 dv.py "C:\\" --save "C:\THOMAS_LOCAL\save"`

and get a folder with an index.html as a result. When trying to open this, I get "No plot specified" as a message? Am I doing something wrong? This is on Chrome. In Edge, it shows the loading screen forever (For 5 minutes now...)

**Comment by zdandoh** [comment]
Use --save-and-host if you want a plug and play solution. The web UI needs to read the data it has generated off the disk, so just opening the HTML file won't work.

**Comment by kasuteru** [comment]
Thanks for the quick reply. I can't use --save-and-host since I need the script to index a cloud environment. However, I looked at the code and managed to get the python part responsible for hosting the server running.

For anyone with the same problem, do the following:

```
os.chdir(r"path_to_save_folder")
server = HTTPServer(("localhost", 8000), Server)
try:
            server.serve_forever()
except KeyboardInterrupt:
            sys.exit("\nStopped")
```
