### ISSUE TITLE
No close server instructions

### ISSUE THREAD

**Issue by twpnnl** [ARM-DOE/dv#8]
When running `dv` with the `-sh` option, there are no instructions on how to close the server. When I close it with `CTRL-C` it gives me a nasty error message:
```python
Traceback (most recent call last):
  File "./dv.py", line 317, in <module>
    server.serve_forever()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

[APM](https://github.com/ARM-DOE/apm/blob/master/apm.py#L1336) has a `signal_handler()` function that handles `CTRL-C` keyboard presses gracefully that would make this look like you were meant to use `CTRL-C` to close it if you want. Regardless it would be good to put some instructions on how to close the server when done with it so the user knows what to do.

**Comment by zdandoh** [comment]
Thanks. I added a little message about how to stop the server. If you Ctrl+C it'll just say "Stopped" instead of giving that error. I ended up going with a catch of KeyboardInterrupt so that I could still have Ctrl+C errors everywhere else.
